GpupoCamelSpiderReaderBundle_homepage:
    pattern:  /all
    defaults: { _controller: GpupoCamelSpiderReaderBundle:Default:index }

GpupoCamelSpiderReaderBundle_folder:
    pattern:  /{type}/{id}
    defaults: { _controller: GpupoCamelSpiderReaderBundle:Default:folder }


