GpupoCamelSpiderReaderBundle_homepage:
    pattern:  /
    defaults: { _controller: GpupoCamelSpiderReaderBundle:Default:index }

GpupoCamelSpiderReaderBundle_folder:
    pattern:  /folder/{type}/{id}
    defaults: { _controller: GpupoCamelSpiderReaderBundle:Default:folder }

GpupoCamelSpiderReaderBundle_news:
    pattern:  /news/{news_id}.{_format}
    defaults: { _controller: GpupoCamelSpiderReaderBundle:Default:news, _format: html }

GpupoCamelSpiderReaderBundle_news_send:
    pattern:  /news/{news_id}/send
    defaults: { _controller: GpupoCamelSpiderReaderBundle:Default:send }


